name: artisan-ai
channels:
  - defaults
dependencies:
  - numpy
  - openai
  - pandas
  - pip
  - python-dotenv
  - streamlit
  - pip:
    - chardet
    - faiss-cpu
    - langchain
    - pypdf
    - streamlit-chat
    - tiktoken